trigger: none
pr: none
resources:
  webhooks:
  - webhook: WebhookPRtest         
    connection: WebhookPRtestConnection
    filters:
    - path: "action"
      value: "labeled"
      
variables:
  - name: AZURE_WEBAPP_NAME
    value: '${{parameters.WebhookPRtest.pull_request.id}}-variant1'
  - name: AZURE_WEBAPPB_NAME
    value: '${{parameters.WebhookPRtest.pull_request.id}}-variant2'
  - name: AZURE_RESOURCE_GROUP
    value: 'POCNextJS'
  - name: LOCATION
    value: 'eastus2'
  - name: NEXT_PUBLIC_MESSAGE
    value: 'test MSG'
  - name: StaticEmptyWebApp
    value: 'TestStaticWebApp'
  - name: ACR_NAME
    value: 'testnextjs'
  - name: APP_SERVICE_PLAN_NAME
    value: 'testnextJSdummy'
    
stages:
- stage: BuildAndDeploy
  jobs:
  - job: DeployStaticPREnvironment
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: templates/label-to-check.yaml
      parameters:
        labelToCheck: 'Create Static Variant1'
        variableName: 'createEnvironmentFound'
        prLabels: ${{ parameters.WebhookPRtest.pull_request.labels }}

    - template: templates/label-to-check.yaml
      parameters:
        labelToCheck: 'Create Static Variant2'
        variableName: 'createEnvironmentBFound'
        prLabels: ${{ parameters.WebhookPRtest.pull_request.labels }}
    
    - template: templates/label-to-check.yaml
      parameters:
        labelToCheck: 'Create Variant1'
        variableName: 'createEnvironmentWAFound'
        prLabels: ${{ parameters.WebhookPRtest.pull_request.labels }}

    - template: templates/label-to-check.yaml
      parameters:
        labelToCheck: 'Create Variant2'
        variableName: 'createEnvironmentWABFound'
        prLabels: ${{ parameters.WebhookPRtest.pull_request.labels }}


    # Static Web App checks
    - template: templates/swa-check-template.yaml
      parameters:
        variantNumber: '1'
        createEnvironmentVarName: 'createEnvironmentFound'
        azureSubscription: 'radek-padrta-vs-msp'
        staticWebAppName: '$(StaticEmptyWebApp)'
        prId: '${{ parameters.WebhookPRtest.pull_request.id }}'

    - template: templates/swa-check-template.yaml
      parameters:
        variantNumber: '2'
        createEnvironmentVarName: 'createEnvironmentBFound'
        azureSubscription: 'radek-padrta-vs-msp'
        staticWebAppName: '$(StaticEmptyWebApp)'
        prId: '${{ parameters.WebhookPRtest.pull_request.id }}'

    # Web App checks
    - template: templates/wa-check-template.yaml
      parameters:
        variantNumber: '1'
        createEnvironmentVarName: 'createEnvironmentWAFound'
        azureSubscription: 'radek-padrta-vs-msp'
        webAppName: '$(AZURE_WEBAPP_NAME)'
        resourceGroup: '$(AZURE_RESOURCE_GROUP)'

    - template: templates/wa-check-template.yaml
      parameters:
        variantNumber: '2'
        createEnvironmentVarName: 'createEnvironmentWABFound'
        azureSubscription: 'radek-padrta-vs-msp'
        webAppName: '$(AZURE_WEBAPPB_NAME)'
        resourceGroup: '$(AZURE_RESOURCE_GROUP)'


    - task: GitHubComment@0
      displayName: 'Comment GH - Starting Static Variant1'
      condition: and(eq(variables['createEnvironmentFound'], 'true'), eq(variables['CheckVariant1.VARIANT1_EXISTS'], 'false'))
      inputs:
        gitHubConnection: 'github-nextjsdummytest'
        repositoryName: '$(Build.Repository.Name)'
        id: '${{parameters.WebhookPRtest.number}}'
        comment: |
          🚀 **Creation Started for Static VARIANT1**
          - The static web app creation process has been initiated.
          - This operation typically takes a few minutes to complete.
          - A follow-up comment will be posted here when the process is complete.
    - task: GitHubComment@0
      displayName: 'Comment GH - Starting Static Variant2'
      condition: and(eq(variables['createEnvironmentBFound'], 'true'), eq(variables['CheckVariant2.VARIANT2_EXISTS'], 'false'))
      inputs:
        gitHubConnection: 'github-nextjsdummytest'
        repositoryName: '$(Build.Repository.Name)'
        id: '${{parameters.WebhookPRtest.number}}'
        comment: |
          🚀 **Creation Started for Static VARIANT2**
          - The static web app creation process has been initiated.
          - This operation typically takes a few minutes to complete.
          - A follow-up comment will be posted here when the process is complete.
    
    - task: AzureCLI@2
      displayName: createEmptyWebApp
      inputs:
        azureSubscription: 'radek-padrta-vs-msp'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Create empty Azure Static Web App
          
          az staticwebapp create \
            --name $(StaticEmptyWebApp) \
            --resource-group $(AZURE_RESOURCE_GROUP) \
            --location $(LOCATION) \
            --sku Free \
            --output none
          
          # Get the deployment token (API token)
          token=$(az staticwebapp secrets list \
            --name $(StaticEmptyWebApp) \
            --resource-group $(AZURE_RESOURCE_GROUP) \
            --query "properties.apiKey" -o tsv)
          
          # Store the token as a pipeline variable
          echo "##vso[task.setvariable variable=AZURE_STATIC_WEB_APP_API_TOKEN;isSecret=true]$token"
          
          # Output the web app name for future reference
          echo "##vso[task.setvariable variable=AZURE_STATIC_WEB_APP_NAME;isOutput=true]$(StaticEmptyWebApp)"
          
          # Print the web app name and a masked version of the token for debugging
          echo "Created empty Static Web App: $(StaticEmptyWebApp)"
          echo "API token (masked): ${token:0:5}...${token: -5}"

    - checkout: self
      submodules: true
    - task: AzureStaticWebApp@0
      name: "buildVariant1"
      condition: eq(variables['CheckVariant1.VARIANT1_EXISTS'], 'false')
      inputs:
        app_location: '/'
        api_location: ''
        output_location: '.next'
        azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APP_API_TOKEN)
        deployment_environment: '${{parameters.WebhookPRtest.pull_request.id}}v1'

    - task: AzureStaticWebApp@0
      name: "buildVariant2"
      condition: eq(variables['CheckVariant2.VARIANT2_EXISTS'], 'false')
      inputs:
        app_location: '/variant2'
        api_location: ''
        output_location: '.next'
        azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APP_API_TOKEN)
        deployment_environment: '${{parameters.WebhookPRtest.pull_request.id}}v2'

    - task: AzureCLI@2
      name: GetVariant1URL
      inputs:
        azureSubscription: 'radek-padrta-vs-msp'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          URL=$(az staticwebapp environment list -n $(StaticEmptyWebApp) -o tsv --query "[?buildId=='variant1'].hostname")
          echo "##vso[task.setvariable variable=VARIANT1_URL;isOutput=true]$URL"

    - task: AzureCLI@2
      name: GetVariant2URL
      inputs:
        azureSubscription: 'radek-padrta-vs-msp'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          URL=$(az staticwebapp environment list -n $(StaticEmptyWebApp)  -o tsv --query "[?buildId=='variant2'].hostname")
          echo "##vso[task.setvariable variable=VARIANT2_URL;isOutput=true]$URL"

    - task: GitHubComment@0
      displayName: 'Comment GH - Static Variant1 Deployed'
      condition: eq(variables['createEnvironmentFound'], 'true')
      inputs:
        gitHubConnection: 'github-nextjsdummytest'
        repositoryName: '$(Build.Repository.Name)'
        id: '${{parameters.WebhookPRtest.number}}'
        comment: |
          ✅ **Static Web App VARIANT1 is ready!**
          You can access the application at $(GetVariant1URL.VARIANT1_URL)
          You can access the application at https://$(GetVariant1URL.VARIANT1_URL)
          Thank you for your patience!

    - task: GitHubComment@0
      displayName: 'Comment GH - Static Variant2 Deployed'
      condition: eq(variables['createEnvironmentBFound'], 'true')
      inputs:
        gitHubConnection: 'github-nextjsdummytest'
        repositoryName: '$(Build.Repository.Name)'
        id: '${{parameters.WebhookPRtest.number}}'
        comment: |
          ✅ **Static Web App VARIANT2 is ready!**
          You can access the application at $(GetVariant2URL.VARIANT2_URL)
          You can access the application at https://$(GetVariant2URL.VARIANT2_URL)
          Thank you for your patience!