trigger: none
pr: none
resources:
  webhooks:
  - webhook: WebhookPRtest         
    connection: WebhookPRtestConnection
    filters:
    - path: "action"
      value: "labeled"
      
variables:
  - name: AZURE_WEBAPP_NAME
    value: '${{parameters.WebhookPRtest.pull_request.id}}-variant1'
  - name: AZURE_WEBAPPB_NAME
    value: '${{parameters.WebhookPRtest.pull_request.id}}-variant2'
  - name: AZURE_RESOURCE_GROUP
    value: 'POCNextJS'
  - name: LOCATION
    value: 'eastus2'
  - name: NEXT_PUBLIC_MESSAGE
    value: 'test MSG'
  - name: StaticEmptyWebApp
    value: 'TestStaticWebApp'
  - name: ACR_NAME
    value: 'testnextjs'
  - name: APP_SERVICE_PLAN_NAME
    value: 'testnextJSdummy'
    
stages:
- stage: BuildAndDeploy
  jobs:
  - job: DeployStaticPREnvironment
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: templates/label-to-check.yaml
      parameters:
        labelToCheck: 'Create Static Variant1'
        variableName: 'createEnvironmentFound'
        prLabels: ${{ parameters.WebhookPRtest.pull_request.labels }}

    - template: templates/label-to-check.yaml
      parameters:
        labelToCheck: 'Create Static Variant2'
        variableName: 'createEnvironmentBFound'
        prLabels: ${{ parameters.WebhookPRtest.pull_request.labels }}
    
    - template: templates/label-to-check.yaml
      parameters:
        labelToCheck: 'Create Variant1'
        variableName: 'createEnvironmentWAFound'
        prLabels: ${{ parameters.WebhookPRtest.pull_request.labels }}

    - template: templates/label-to-check.yaml
      parameters:
        labelToCheck: 'Create Variant2'
        variableName: 'createEnvironmentWABFound'
        prLabels: ${{ parameters.WebhookPRtest.pull_request.labels }}


    # Static Web App checks
    - template: templates/swa-check-template.yaml
      parameters:
        variantNumber: '1'
        createEnvironmentVarName: 'createEnvironmentFound'
        azureSubscription: 'radek-padrta-vs-msp'
        staticWebAppName: '$(StaticEmptyWebApp)'
        prId: '${{ parameters.WebhookPRtest.pull_request.id }}'

    - template: templates/swa-check-template.yaml
      parameters:
        variantNumber: '2'
        createEnvironmentVarName: 'createEnvironmentBFound'
        azureSubscription: 'radek-padrta-vs-msp'
        staticWebAppName: '$(StaticEmptyWebApp)'
        prId: '${{ parameters.WebhookPRtest.pull_request.id }}'

    # Web App checks
    - template: templates/wa-check-template.yaml
      parameters:
        variantNumber: '1'
        createEnvironmentVarName: 'createEnvironmentWAFound'
        azureSubscription: 'radek-padrta-vs-msp'
        webAppName: '$(AZURE_WEBAPP_NAME)'
        resourceGroup: '$(AZURE_RESOURCE_GROUP)'

    - template: templates/wa-check-template.yaml
      parameters:
        variantNumber: '2'
        createEnvironmentVarName: 'createEnvironmentWABFound'
        azureSubscription: 'radek-padrta-vs-msp'
        webAppName: '$(AZURE_WEBAPPB_NAME)'
        resourceGroup: '$(AZURE_RESOURCE_GROUP)'

    # GitHub Comments
    - template: templates/github-comment-template.yml
      parameters:
        variantNumber: '1'
        createEnvironmentVarName: 'createEnvironmentFound'
        variantExistsVarName: 'CheckVariant1.VARIANT1_EXISTS'
        gitHubConnection: 'github-nextjsdummytest'
        prNumber: '${{ parameters.WebhookPRtest.number }}'
    
    - template: templates/github-comment-template.yml
      parameters:
        variantNumber: '2'
        createEnvironmentVarName: 'createEnvironmentBFound'
        variantExistsVarName: 'CheckVariant2.VARIANT2_EXISTS'
        gitHubConnection: 'github-nextjsdummytest'
        prNumber: '${{ parameters.WebhookPRtest.number }}'
    
    - task: AzureCLI@2
      displayName: createEmptyWebApp
      inputs:
        azureSubscription: 'radek-padrta-vs-msp'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Create empty Azure Static Web App
          
          az staticwebapp create \
            --name $(StaticEmptyWebApp) \
            --resource-group $(AZURE_RESOURCE_GROUP) \
            --location $(LOCATION) \
            --sku Free \
            --output none
          
          # Get the deployment token (API token)
          token=$(az staticwebapp secrets list \
            --name $(StaticEmptyWebApp) \
            --resource-group $(AZURE_RESOURCE_GROUP) \
            --query "properties.apiKey" -o tsv)
          
          # Store the token as a pipeline variable
          echo "##vso[task.setvariable variable=AZURE_STATIC_WEB_APP_API_TOKEN;isSecret=true]$token"
          
          # Output the web app name for future reference
          echo "##vso[task.setvariable variable=AZURE_STATIC_WEB_APP_NAME;isOutput=true]$(StaticEmptyWebApp)"
          
          # Print the web app name and a masked version of the token for debugging
          echo "Created empty Static Web App: $(StaticEmptyWebApp)"
          echo "API token (masked): ${token:0:5}...${token: -5}"

    - checkout: self
      submodules: true
    - task: AzureStaticWebApp@0
      name: "buildVariant1"
      condition: eq(variables['CheckVariant1.VARIANT1_EXISTS'], 'false')
      inputs:
        app_location: '/'
        api_location: ''
        output_location: '.next'
        azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APP_API_TOKEN)
        deployment_environment: '${{parameters.WebhookPRtest.pull_request.id}}v1'

    - task: AzureStaticWebApp@0
      name: "buildVariant2"
      condition: eq(variables['CheckVariant2.VARIANT2_EXISTS'], 'false')
      inputs:
        app_location: '/variant2'
        api_location: ''
        output_location: '.next'
        azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APP_API_TOKEN)
        deployment_environment: '${{parameters.WebhookPRtest.pull_request.id}}v2'

    - template: templates/get-url-template.yml
      parameters:
        variantNumber: '1'
        azureSubscription: 'radek-padrta-vs-msp'
        staticWebAppName: '$(StaticEmptyWebApp)'
    
    - template: templates/get-url-template.yml
      parameters:
        variantNumber: '2'
        azureSubscription: 'radek-padrta-vs-msp'
        staticWebAppName: '$(StaticEmptyWebApp)'
    
    # Final GitHub Comments
    - template: templates/final-github-comment-template.yml
      parameters:
        variantNumber: '1'
        createEnvironmentVarName: 'createEnvironmentFound'
        gitHubConnection: 'github-nextjsdummytest'
        prNumber: '${{ parameters.WebhookPRtest.number }}'
        urlVarName: 'GetVariant1URL.VARIANT1_URL'
    
    - template: templates/final-github-comment-template.yml
      parameters:
        variantNumber: '2'
        createEnvironmentVarName: 'createEnvironmentBFound'
        gitHubConnection: 'github-nextjsdummytest'
        prNumber: '${{ parameters.WebhookPRtest.number }}'
        urlVarName: 'GetVariant2URL.VARIANT2_URL'