name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_SKY_0C250A80F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: ".next"
      
      - name: Debug Info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Event action: ${{ github.event.action }}"
          echo "Is PR? ${{ github.event_name == 'pull_request' }}"
          echo "PR number: ${{ github.event.number }}"
      
      - name: Show URL
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "Preview URL: ${{ steps.builddeploy.outputs.preview_url }}"
          else
            echo "Production URL: ${{ steps.builddeploy.outputs.static_web_app_url }}"
          fi
      
      - name: Comment PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const previewUrl = '${{ steps.builddeploy.outputs.preview_url }}';
            console.log('Preview URL for PR comment:', previewUrl);
            if (previewUrl) {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.name,
                body: `📢 Preview this PR: ${previewUrl}`
              });
              console.log('PR comment created successfully');
            } else {
              console.log('No preview URL available, skipping PR comment');
            }

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_SKY_0C250A80F }}
          action: "close"
