name: Turbo CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

env:
  AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_HILL_01E38BE0F }}

permissions:
  contents: read
  pull-requests: write

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build affected apps
        run: npx turbo run build --filter=[HEAD^1]

      - name: Check for changes in variant1
        id: check_variant1
        run: |
          git diff --name-only HEAD^ HEAD | grep -q "^variant1/" && echo "changed=true" >> $GITHUB_OUTPUT || echo "changed=false" >> $GITHUB_OUTPUT

      - name: Check for changes in variant2
        id: check_variant2
        run: |
          git diff --name-only HEAD^ HEAD | grep -q "^variant2/" && echo "changed=true" >> $GITHUB_OUTPUT || echo "changed=false" >> $GITHUB_OUTPUT

      - name: Deploy variant1
        if: steps.check_variant1.outputs.changed == 'true'
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "variant1"
          output_location: ".next"
          app_build_command: "npm run build"
          deployment_environment: variant1-${{ github.event.number }}

      - name: Deploy variant2
        if: steps.check_variant2.outputs.changed == 'true'
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "variant2"
          output_location: ".next"
          app_build_command: "npm run build"
          deployment_environment: variant2-${{ github.event.number }}

      - name: Comment PR
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const variant1Changed = '${{ steps.check_variant1.outputs.changed }}' === 'true';
            const variant2Changed = '${{ steps.check_variant2.outputs.changed }}' === 'true';
            
            let comment = '## Preview Environments\n\n';
            if (variant1Changed) {
              comment += '- Variant 1: https://variant1-${{ github.event.number }}.azurestaticapps.net\n';
            }
            if (variant2Changed) {
              comment += '- Variant 2: https://variant2-${{ github.event.number }}.azurestaticapps.net\n';
            }
            if (!variant1Changed && !variant2Changed) {
              comment += 'No changes detected in either variant. No new preview environments were created.\n';
            }
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            })

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"