name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Determine app location
        id: app_location
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            LABELS=$(jq -r '.pull_request.labels[].name' "$GITHUB_EVENT_PATH")
            if echo "$LABELS" | grep -q "variant2"; then
              echo "APP_LOCATION=/variant2" >> $GITHUB_OUTPUT
            else
              echo "APP_LOCATION=/" >> $GITHUB_OUTPUT
            fi
          else
            echo "APP_LOCATION=/" >> $GITHUB_OUTPUT
          fi

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_HILL_01E38BE0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ steps.app_location.outputs.APP_LOCATION }}
          api_location: ""
          output_location: ".next"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_HILL_01E38BE0F }}
          action: "close"
