name: Azure Static Web Apps CI/CD with Turbo

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Determine app to build
        id: determine_app
        run: |
          if turbo run build --filter=variant2...[origin/main]; then
            echo "APP_LOCATION=variant2" >> $GITHUB_OUTPUT
          elif turbo run build --filter=variant1...[origin/main]; then
            echo "APP_LOCATION=variant1" >> $GITHUB_OUTPUT
          else
            echo "APP_LOCATION=variant1" >> $GITHUB_OUTPUT
          fi

      - name: Build app
        run: turbo run build --filter=${{ steps.determine_app.outputs.APP_LOCATION }}

      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_HILL_01E38BE0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "${{ steps.determine_app.outputs.APP_LOCATION }}"
          api_location: ""
          output_location: ".next"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_HILL_01E38BE0F }}
          action: "close"
